# Generated by Django 5.2.3 on 2025-07-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Book Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Price (₦)')),
                ('add_date', models.DateTimeField(auto_now=True, verbose_name='Date Added')),
                ('cover', models.ImageField(upload_to='covers', verbose_name='Cover Image')),
            ],
        ),
    ]
